In [ ]:
Python
|->Programming Language
     |=> download python from https://www.python.org = CPython - we can do python programming 
                                                       --------
     Python - everything is a class object design model
              ..........
               10 <== is an object - belongs to int class
               'ab' <== is an object - belongs to str class
              10.0 <== floating object - float class
               True /False <== bool class
     containers 
        - list tuple dict set
          ===============

    |-> download python from https://www.anaconda.com/download 
                            ---------------------------------
                we can do python + DataScience + ML modules - available 

In [1]:
print(type(10))

<class 'int'>


In [2]:
i = 10
j = 4+6
k = 2+8
l = 3+7

print(hex(id(i)))
print(hex(id(j)))
print(hex(id(k)))
print(hex(id(l)))

0x7ffe10f3b4c8
0x7ffe10f3b4c8
0x7ffe10f3b4c8
0x7ffe10f3b4c8


In [3]:
import sys
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

In [ ]:
product
 |-> productID       - 101       = int    => product_id = 101
 |-> productName     - 'pA'      = str    => product_name = 'pA'
 |-> productCost     - 1000.32   = float  => product_cost = 1000.32
 |-> productSales    - True      = bool   => product_Sales = True
Vs
product_info1 = [101,'pA',1000.32,True] <== list - Collection of different types of items - mutable 
                                                 - we can add/modify/delete
Vs
product_info2 = (101,'pA',1000.32,True) <== tuple - Collection of different types of items - immutable
                                                  - we can't add/modify/delete

Vs
product_info3 = {'pid':101,'pname':'pA','pcost':1000.32,'pstatus':True} <== dict
                - Collection of different types of items - mutable
                - - we can add/modify/delete

In [4]:
# Given List 
product_info1 = [101,'pA',1000.32,True]

print(type(product_info1))

<class 'list'>


In [5]:
print(product_info1[0])
print(product_info1[1])
print(product_info1[-1])

101
pA
True


In [6]:
product_info1[2]

1000.32

In [7]:
# To modify
product_info1[2] = 4590.32 

In [8]:
print(product_info1)

[101, 'pA', 4590.32, True]


In [9]:
# tuple - record 
product_info2 = (101,'pA',1000.32,True) # immutable
print(type(product_info2))

<class 'tuple'>


In [10]:
product_info2

(101, 'pA', 1000.32, True)

In [11]:
product_info2[0]

101

In [12]:
product_info2[-1]

True

In [13]:
product_info3 = {'pid':101,'pname':'pA','pcost':1000.32,'pstatus':True}
print(type(product_info3))

<class 'dict'>


In [14]:
product_info3['pid']

101

In [15]:
product_info3['pcost']

1000.32

In [16]:
product_info3['pcost'] = 5689.42 # we can modify an existing value

In [17]:
product_info3

{'pid': 101, 'pname': 'pA', 'pcost': 5689.42, 'pstatus': True}

In [ ]:
list,dict - mutable 

list,dict
...................................
list of list  => [ [],[],[],[] ]
list of dict  => [ {},{},{},{} ] 
dict of list  => { 'key1': [], 'key2':[] ... 'Kn':[] } <=== 
dict of dict  => { 'Key1': {} , 'Key2':{} }
...................................

In [18]:
# list of list
product_list = [[101,'pA',1000],[102,'pB',2000],[103,'pC',3000]]
product_list

[[101, 'pA', 1000], [102, 'pB', 2000], [103, 'pC', 3000]]

In [19]:
product_list.append([104,'pD',3450])
product_list

[[101, 'pA', 1000], [102, 'pB', 2000], [103, 'pC', 3000], [104, 'pD', 3450]]

In [20]:
print(product_list[0])
print(product_list[1])

[101, 'pA', 1000]
[102, 'pB', 2000]


In [21]:
print(product_list[1][0])

102


In [23]:
# list of dict
product_list = [{'pid':101,'pname':'pA','pcost':1000},
                {'pid':102,'pname':'pB','pcost':2000},
                {'pid':103,'pname':'pC','pcost':3000}
               ]

In [24]:
product_list[0]

{'pid': 101, 'pname': 'pA', 'pcost': 1000}

In [25]:
product_list[0]['pname'] # list of dict

'pA'

In [26]:
L = [["D1","D2","D3"],{"K1":"D4","K2":"D5"}]
L

[['D1', 'D2', 'D3'], {'K1': 'D4', 'K2': 'D5'}]

In [ ]:
# Create a product list - productName,productID,productCost
# -----------------------
# dict of list => d={'Key1':[]}
#
# dict of dict => d={'Key1':{}}

In [27]:
products = {}

products['pid'] = []
products['pname'] = []
products['pcost'] = []
products

{'pid': [], 'pname': [], 'pcost': []}

In [28]:
products['pid'].append(101)
products['pname'].append('pA')
products['pcost'].append(1000)
products

{'pid': [101], 'pname': ['pA'], 'pcost': [1000]}

In [29]:
products['pid'].append(102)
products['pname'].append('pB')
products['pcost'].append(2000)
products['pid'].append(103)
products['pname'].append('pC')
products['pcost'].append(3000)

In [30]:
products

{'pid': [101, 102, 103],
 'pname': ['pA', 'pB', 'pC'],
 'pcost': [1000, 2000, 3000]}

In [31]:
# dict of dict

products={}
products['K1']={'pid':101,'pname':'pA','pcost':1000}
products['K2']={'pid':102,'pname':'pB','pcost':2000}
products['K3']={'pid':103,'pname':'pC','pcost':3000}
products['K4']={'pid':104,'pname':'pD','pcost':4000}
products

{'K1': {'pid': 101, 'pname': 'pA', 'pcost': 1000},
 'K2': {'pid': 102, 'pname': 'pB', 'pcost': 2000},
 'K3': {'pid': 103, 'pname': 'pC', 'pcost': 3000},
 'K4': {'pid': 104, 'pname': 'pD', 'pcost': 4000}}

In [32]:
products['K1']

{'pid': 101, 'pname': 'pA', 'pcost': 1000}

In [33]:
products['K1']['pname']

'pA'

In [ ]:
[
  {
    "login": "ggobi",
    "id": 423638,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjQyMzYzOA==",
    "url": "https://api.github.com/orgs/ggobi",
    "repos_url": "https://api.github.com/orgs/ggobi/repos",
    "events_url": "https://api.github.com/orgs/ggobi/events",
    "hooks_url": "https://api.github.com/orgs/ggobi/hooks",
    "issues_url": "https://api.github.com/orgs/ggobi/issues",
    "members_url": "https://api.github.com/orgs/ggobi/members{/member}",
    "public_members_url": "https://api.github.com/orgs/ggobi/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/423638?v=4",
    "description": ""
  }
]

In [ ]:
numpy   - Computation
  |-> index , slicing , reshaping
  |-> ufunctions 

pandas  - Analysis
  |-> Series
  |-> DataFrame 

matplotlib - Visualization
 |-> plot,scatter,bar,pie,....

In [34]:
L=[10,20,30,40,50]
L+100

TypeError: can only concatenate list (not "int") to list

In [36]:
import numpy
numpy.array([])

array([], dtype=float64)

In [37]:
import numpy as np
np.array([])

array([], dtype=float64)

In [38]:
arr = np.array([10,20,30,40,50])
arr+100

array([110, 120, 130, 140, 150])

In [39]:
arr+100.56

array([110.56, 120.56, 130.56, 140.56, 150.56])

In [41]:
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 20 30 40 50]
int64
(5,)
1


In [47]:
print(np.array([10,20,30]).dtype)
print(np.array([10,20,30.0]).dtype)
print(np.array([10,20,True]).dtype)
print(np.array([True,False]).dtype)
print(np.array([10,20,3.5,True]).dtype)
print('')
print(np.array([10,20,'data']).dtype)

int64
float64
int64
bool
float64

<U21


In [48]:
np.array([10,20,30])+100

array([110, 120, 130])

In [49]:
np.array([10,20,'data'])+100

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

In [50]:
np.array([10,20,30]).ndim

1

In [51]:
np.array([[10,20,30]]).ndim

2

In [53]:
arr = np.array([[10,20,30]])
arr.ndim

2

In [55]:
arr

array([[10, 20, 30]])

In [56]:
arr[0]

array([10, 20, 30])

In [57]:
arr[0][0]

np.int64(10)

In [61]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr.ndim,arr.shape)
print(arr)

2 (2, 3)
[[10 20 30]
 [40 50 60]]


In [ ]:
      C1  C2   C3  
row1 10 | 20 | 30
     ---|----|--
row2 40 |50  |60

In [62]:
arr.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [63]:
arr.reshape(1,6)

array([[10, 20, 30, 40, 50, 60]])

In [64]:
arr.reshape(6,1)

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

In [65]:
arr.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [66]:
arr.reshape(-1,1) # Convert to 2D

array([[10],
       [20],
       [30],
       [40],
       [50],
       [60]])

In [ ]:
# numpy universal functions
# ----------------------------
np.mean() => np.mean(data) 
np.median() =>np.median(data) 
np.std() -> np.std(data)
np.max(data)
np.min(data)
np.sum(data) - sum of all items


In [69]:
# Python way - Calculate sum of given list

L=[10,20,30,40,50]

total = 0
for var in L:
    total = total + var
print(total)

## Vs
# numpy 
arr = np.array(L)
print(np.sum(arr))

150
150


In [70]:
np.mean(arr)

np.float64(30.0)

In [71]:
np.median(arr)

np.float64(30.0)

In [72]:
arr = np.array([[1,2,3],[4,5,6]])

print(np.mean(arr))

3.5


In [ ]:
   |  |    |  <== Column = axis=0
--------->--------------
           Row = axis = 1

In [73]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
np.mean(arr,axis=1) # row

array([2., 5.])

In [75]:
np.mean(arr,axis=0) # column

array([2.5, 3.5, 4.5])

In [77]:
products = {'pid':[],'pname':[],'pcost':[]}
products['pid'].append(101)
products['pname'].append('pA')
products['pcost'].append(1000)
products

{'pid': [101], 'pname': ['pA'], 'pcost': [1000]}

In [78]:
products['pid'].append(102)
products['pname'].append('pB')
products['pcost'].append(2000)
products['pid'].append(103)
products['pname'].append('pC')
products['pcost'].append(3000)
products['pid'].append(104)
products['pname'].append('pD')
products['pcost'].append(4000)

In [79]:
products

{'pid': [101, 102, 103, 104],
 'pname': ['pA', 'pB', 'pC', 'pD'],
 'pcost': [1000, 2000, 3000, 4000]}

In [80]:
print(type(products))

<class 'dict'>


In [81]:
products['pcost']

[1000, 2000, 3000, 4000]

In [82]:
arr = np.array(products['pcost']) # ->numpy_array_object
np.sum(arr)

np.int64(10000)

In [83]:
np.max(arr)

np.int64(4000)

In [84]:
np.mean(arr)

np.float64(2500.0)

In [ ]:
###################################################

In [85]:
import pandas
pandas

<module 'pandas' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py'>

In [88]:
print(pandas.Series)

<class 'pandas.core.series.Series'>


In [89]:
print(pandas.DataFrame)

<class 'pandas.core.frame.DataFrame'>


In [ ]:
pandas/
   |___core/
        |__frame.py
               |__class DataFrame:

In [91]:
import pandas as pd
pd.Series([10,20,30,40,50])

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [92]:
pd.DataFrame([10,20,30,40,50])

0
0  10
1  20
2  30
3  40
4  50

In [93]:
products = {}
products['pid'] = [101,102,103]
products['pname'] = ['pA','pB','pC']
products['pcost'] = [1000,2000,3000]
products

{'pid': [101, 102, 103],
 'pname': ['pA', 'pB', 'pC'],
 'pcost': [1000, 2000, 3000]}

In [94]:
pd.DataFrame(products)

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000

In [95]:
df1 = pd.DataFrame(products)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   pid     3 non-null      int64 
 1   pname   3 non-null      object
 2   pcost   3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes


In [96]:
df1.index

RangeIndex(start=0, stop=3, step=1)

In [97]:
df1.columns

Index(['pid', 'pname', 'pcost'], dtype='object')

In [ ]:
# To fetch data - row based => df.loc[index] -> record 
#
# To fetch data - column based -> df['ColumnName'] -> column
#                                 -like dictName['key']

In [98]:
df1.loc[1]

pid       102
pname      pB
pcost    2000
Name: 1, dtype: object

In [99]:
df1.loc[0]

pid       101
pname      pA
pcost    1000
Name: 0, dtype: object

In [101]:
df1.loc[1]

pid       102
pname      pB
pcost    2000
Name: 1, dtype: object

In [102]:
df1['pid']

0    101
1    102
2    103
Name: pid, dtype: int64

In [103]:
df1['pname']

0    pA
1    pB
2    pC
Name: pname, dtype: object

In [104]:
df1.loc[1]['pname']

'pB'

In [ ]:
# add more products to product_structure(dict) - do append operation
# |->initialize to DataFrame ->new_df 
#                                 |->Fetch Row X Column 

In [105]:
products = {}
products['pid'] = [101,102,103]
products['pname'] = ['pA','pB','pC']
products['pcost'] = [1000,2000,3000]


In [106]:
products['pid'].append(104)
products['pname'].append('pD')
products['pcost'].append(4000)

products['pid'].append(105)
products['pname'].append('pE')
products['pcost'].append(5000)

products['pid'].append(106)
products['pname'].append('pF')
products['pcost'].append(6000)

products['pid'].append(107)
products['pname'].append('pG')
products['pcost'].append(2300)

products['pid'].append(108)
products['pname'].append('pH')
products['pcost'].append(3400)

In [108]:
df2 = pd.DataFrame(products)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   pid     8 non-null      int64 
 1   pname   8 non-null      object
 2   pcost   8 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 324.0+ bytes


In [109]:
df2['pid']

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
Name: pid, dtype: int64

In [110]:
df2.loc[2]

pid       103
pname      pC
pcost    3000
Name: 2, dtype: object

In [111]:
df2.loc[2:] # from 2nd row to list of all - Slicing

pid pname  pcost
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pF   6000
6  107    pG   2300
7  108    pH   3400

In [112]:
df2.loc[2:5] # from 2nd row - 5th row

pid pname  pcost
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pF   6000

In [113]:
df2.loc[3]['pname']

'pD'

In [115]:
df2.loc[3][['pname','pcost']]

pname      pD
pcost    4000
Name: 3, dtype: object

In [118]:
df2.loc[2:5][['pname','pcost']] # from 2nd row - 5th row - filter productName,productCost

pname  pcost
2    pC   3000
3    pD   4000
4    pE   5000
5    pF   6000

In [121]:
df2['pcost']
df2['pcost'] * 0.18

0     180.0
1     360.0
2     540.0
3     720.0
4     900.0
5    1080.0
6     414.0
7     612.0
Name: pcost, dtype: float64

In [122]:
df2['pcost'] >3000

0    False
1    False
2    False
3     True
4     True
5     True
6    False
7     True
Name: pcost, dtype: bool

In [123]:
df2[df2['pcost'] >3000] # boolean index - filter True values/records only

pid pname  pcost
3  104    pD   4000
4  105    pE   5000
5  106    pF   6000
7  108    pH   3400

In [ ]:
# In pandas DataFrame - mutable - inplace=True <== modified input DataFrame

In [124]:
# To delete a particular row/record 
# df.drop(rowIndex)
len(df2.index)

8

In [125]:
df2.drop(3) # delete 3rd row

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
4  105    pE   5000
5  106    pF   6000
6  107    pG   2300
7  108    pH   3400

In [126]:
len(df2.index)

8

In [127]:
df2

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pF   6000
6  107    pG   2300
7  108    pH   3400

In [128]:
df3 = df2.drop(3)
print(len(df3.index))
print(len(df2.index))

7
8


In [129]:
df2.drop(4,inplace=True) # ->None. But dataframe is updated

In [130]:
len(df2.index)

7

In [131]:
df2

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
3  104    pD   4000
5  106    pF   6000
6  107    pG   2300
7  108    pH   3400

In [ ]:
######## 